version: '3.9'
services:
  postgresqlServer:
      image: postgres:16.2-alpine3.19
      volumes:
        - postgresqlData:/var/lib/postgresql/data
      environment:
        - POSTGRES_USER=test
        - POSTGRES_PASSWORD=test
        - POSTGRES_DB=test
      ports:
        - "4848:5432"
volumes:
  postgresqlData:
    driver: local
